--- #YAML:1.0
name:               Net-Syslogd
version:            0.04
abstract:           Perl implementation of Syslog Listener
author:
    - Michael Vincent <vin at vinsworld dot com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket:    ~
    Test::Simple:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
